" VIM SETTINGS FILE (GUI)
" ================================================================

" appearance
colorscheme solarized
set guifont=PragmataPro:h14
set background=light

" use visual bell
set vb
