" VIM SETTINGS FILE (GUI)
" ================================================================

" appearance
colorscheme base16-default-light
set guifont=PragmataPro:h13
set background=light

" use visual bell
set vb
