" VIM SETTINGS FILE (GUI)
" ================================================================

" appearance
colorscheme macvim
set guifont=SFMono-Regular:h13
set background=light

" use visual bell
set vb
