# vim:ft=zsh

# https://support.apple.com/en-us/HT208050
# -> .zprofile is equivalent to .bash_profile and runs at login, including over SSH
# https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc

# consolidate `.zshrc` and `zprofile`
if [ -f $HOME/.zshrc ]; then
  source $HOME/.zshrc
fi

